export enum AcaoEnum {
  VENDA = 'VENDA',
  COMPRA = 'COMPRA',
  DEVOLUCAO_DO_CLIENTE = 'DEVOLUCAO_DO_CLIENTE',
  DEVOLUCAO_AO_FORNECEDOR = 'DEVOLUCAO_AO_FORNECEDOR',
  PRODUTO_QUEBRADO = 'PRODUTO_QUEBRADO',
}
